import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import AuthProvider from "@/providers/auth-provider";
import { auth } from "@/auth";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import QueryProvider from "@/providers/query";

const inter = Rubik({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Certifolio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <AuthProvider session={session}>
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <QueryProvider>
            <NextTopLoader
              showSpinner
              template='<div class="bar" role="bar"><div class="peg"></div></div>
                <div class="spinner" role="spinner"><div class="spinner-icon fixed bottom-0 right-0 m-2"></div></div>'
            />
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
              {children}
              {modal}
              <Toaster />
            </ThemeProvider>
          </QueryProvider>
        </body>
      </html>
    </AuthProvider>
  );
}
